### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Confidant23** [SigPloiter/SigPloit#106]
Confession:I'm not a python programmer, just  a newbie wandering around.

I tried  running Sigploit.py and was denied saying that the "fraud" module was missing.
I just deleted the line "import fraud" from Sigploit.py and then was able to execute successfully.
 
I selected "SS7" module followed by"Simulation mode" I was prompted to run a server(I have no idea what that was).
then, I selected "location tracking" and AnyTimeInterrogation and nothing happened, I was displayed "AnyTimeInterrogation.jar"  failed to launch and the program returned to the main menu.

The same happened when I tried SMS interception and other options.
please help me   Thanks in advance.

**Comment by SigPloiter** [comment]
@Confidant23 no problem at all we are all newbies :), anyways i have removed the "import fraud" and removed its corresponding function till its ready, thanks for notifying 

second find a detailed explanation on how you can use the SS7 module (from the wiki)
Attacking the SS7

In order to attach the SS7 on real life target you should have an access to the SS7 network. It is often provided by VoIP providers, SMS providers, HLR lookup web application providers, you just need to dig deeper to find a suitable provider. The project provides to modes for attacks 1)Simulation Mode 2)Live mode.
Live Mode

In case you succeeded to get the access you can jump into the Live mode and use the parameters that are provided by your provider. The providers will provide you the following parameters

    The global title you will use
    The point code you will use (client PC)
    The peer point code of the provider (Peer PC)
    The IP address of the providers peer for SCTP associations and the used port (Peer IP, Peer Port)

All you need to do is to have a static public IP assigned to the sever/machine having the code and the provider will allow it access from its side and route it so you can reach all the operators this provider is connected to
Simulation Mode

In case of no access, and you need to have the sense of attacks and critically of such a threat, you can go to the simulation mode. The project provides the server side code of each and every attack that simulates the corresponding nodes responsible for the requests. The server side jar files be found under "SigPloit/Testing/Server/Attacks/". Each server side code provides the hard coded values that you need to use on the client side to simulate the attack

The brief explanation:
==================
- As SS7 needs some access to the SS7 cloud of the operators, i made two modes live and simulation, i have also made the server side codes (source codes and jar files available under Testing/Server/Attacks) along with the used parameters in each case in order for you to simulate and get an idea about the attack, how is run, what are the involved nodes in each attack and what are the expeted data returned

In this case (i.e simulation) you need to run sigploit on two different VMs one for client and other for server, depending on the attack you chose , run the server side jar file to simulate the responses

tell me if you need further assistance

**Comment by Confidant23** [comment]
Thanks for your enthusiastic reply.
