### ISSUE TITLE
Simulator cannot assign requested address

### ISSUE THREAD

**Issue by dgellman** [SigPloiter/SigPloit#113]
I am trying to get the SMS Simulator working (UpdateLocation.jar) and i keep seeing the same error java.net.BindException: Cannot assign requested address.  Am I missing something in the configuration or is something broken?

Thanks in advance.

**Comment by SigPloiter** [comment]
Are you sure that your interface is assigned the IP: 192.168.56.101 ?

**Comment by dgellman** [comment]
Thanks for the quick response.  I'm assuming the interface you're referring to is the regular networking interface? Or do I have to enable SCTP interface and assign that IP address?

If regular interface - answer is no, should i recompile the JAR with the proper IP?

If I need to enable a new interface - any docs on how ? I assumed SCTP was enabled by default on Kali.

**Comment by SigPloiter** [comment]
1- First of all make sure to apt-get install libsctp1 libsctp-dev
lksctp-tools
2- you need to run sigploit on two virtual machines (for attacker and
victim, since i assume you dont have an SS7 access, so you need to
intialize each test as specified)
3- by then just change the interfaces on your VMs to host only adpaters and
change the network configuraiton as specified

**Comment by dgellman** [comment]
Awesome! I'll give this a try tonight and post back if it is working. Thanks for the help!

**Comment by dgellman** [comment]
Thanks for the help! I was able to get the server up and running at 192.168.56.102 for the server side.

**Comment by SigPloiter** [comment]
anytime :)
